env_registry:
  Sokoban: vagen.envs.sokoban.sokoban_env.Sokoban
  FrozenLake: vagen.envs.frozenlake.frozenlake_env.FrozenLake
  BrickIsaacPartialView: vagen.envs.isaac_partial_view.isaac_managed_env.IsaacManagedEnv
  BrickIsaacFullView: vagen.envs.isaac.isaac_managed_env.IsaacManagedEnv
